[tools]
node = "lts"
python = "latest"
ruby = "3.2.2"
pdm = "latest"

[env]
npm_config_update_notifier = "false"
npm_config_progress = "false"
npm_config_update_all = "true"
npm_config_loglevel = "warn"
npm_config_unsafe_perm = "true"
