#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Chrome" desktop=2

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

function update_battery_loop() {
	while true; do
		# Get the current battery percentage.
		battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

		if [ $battery -gt 84 ]; then
			yabai -m config status_bar_power_icon_strip battery-full plug
		elif [ $battery -gt 60 ]; then
			yabai -m config status_bar_power_icon_strip battery-three-quarters plug
		elif [ $battery -gt 39 ]; then
			yabai -m config status_bar_power_icon_strip battery-half plug
		elif [ $battery -gt 14 ]; then
			yabai -m config status_bar_power_icon_strip battery-quarter plug
		else
			yabai -m config status_bar_power_icon_strip battery-empty plug
		fi

		# wait 1 minutes
		sleep 1m
	done
}

# run the function async
update_battery_loop &


echo "yabai configuration loaded.."
