#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

# from https://htr3n.github.io/2018/07/faster-zsh/
# Execute code in the background to not affect the current session
(
setopt LOCAL_OPTIONS EXTENDED_GLOB
autoload -U zrecompile
local OHMYZSH=~/.oh-my-zsh

  # Compile zcompdump, if modified, to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
  # zcompile .zshrc
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zshrc
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zprofile
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zshenv
  zrecompile -pq ${ZDOTDIR:-${HOME}}/.zshrc-helpers
  # recompile all zsh or sh
  for f in $OHMYZSH/**/*.*sh
  do
    zrecompile -pq $f
  done
  ) &!

