#_ZSH_PROFILE=1

if [ "$_ZSH_PROFILE" ]; then
  zmodload zsh/zprof
fi
if [[ -d "$HOME/.pyenv" ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path 2> /dev/null)"
fi

# Mise shims ahead of pyenv in path
if [[ -d "$HOME/.local/share/mise/shims" ]]; then
    export PATH="$HOME/.local/share/mise/shims:$PATH"
fi

export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"

if [ "$_ZSH_PROFILE" ]; then
  zprof
fi

# Created by `userpath` on 2025-06-30 03:58:21
export PATH="$PATH:/Users/sauhsoj/Library/Application Support/hatch/pythons/3.13/python/bin"
