#when profiling, uncomment this line
#_ZSH_PROFILE=1

if [ $_ZSH_PROFILE ]; then
  zmodload zsh/zprof
fi

#ensure path arrays do not contain duplicates
typeset -gU cdpath fpath mailpath path

OLDPATH=$PATH
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin


fpath=(~/.zsh/completion $fpath)

source $HOME/.zshrc-helpers

#OktaAWSCLI
if [[ -f "$HOME/.okta/bash_functions" ]]; then
  . "$HOME/.okta/bash_functions"
fi

prepend_path /home/linuxbrew/.linuxbrew/bin
prepend_path /usr/local/opt/coreutils/libexec/gnubin
prepend_path $HOME/.toolbox/bin
append_path  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
prepend_manpath /usr/local/opt/coreutils/libexec/gnuman
append_path $HOME/.cargo/bin
append_path $HOME/.dotnet/tools
append_path $HOME/.pyenv/bin
append_path ${KREW_ROOT:-$HOME/.krew}/bin
export PATH=$PATH:$OLDPATH

ZSH_THEME="agnoster"

HYPHEN_INSENSITIVE="true"
export UPDATE_ZSH_DAYS=5
DISABLE_UPDATE_PROMPT="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
ZSH_TMUX_AUTOSTART=true

plugins=(
  aws
  chucknorris
  command-not-found
  dircycle
  docker
  git
  git-extras
  git-prompt
  gitfast
  github
  gpg-agent
  helm
  history
  kubectl
  kubectx
  magic-enter
  osx
  pyenv
  rbenv
  screen
  sublime
  sublime-merge
  sudo
  vault
  virtualenv
  zsh-interactive-cd
)

export ZSH="$HOME/.sheldon/repos/github.com/ohmyzsh/ohmyzsh"

eval "$(sheldon source)"

zsh-defer eval "$(pyenv init -)"
zsh-defer eval "$(pyenv virtualenv-init -)"

# User configuration

export EDITOR='nvim'

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

[ -f ~/.fzf.zsh ] && zsh-defer source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && zsh-defer source "${HOME}/.iterm2_shell_integration.zsh"

if [ -d $HOME/.nvm ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && zsh-defer source "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && zsh-defer source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

neofetch

if [ $_ZSH_PROFILE ]; then
  zprof
fi

