#!/bin/env zsh
#
# add to back of path
append_path()
{
  if ! [ -d "$1" ]; then return; fi

  case ":$PATH:" in
      *":$1:"*) :;;
      *) PATH=$1:$PATH ;;
    esac
}
# add to front of path
prepend_path()
{
  if ! [ -d "$1" ]; then return; fi

  case ":$PATH:" in
      *":$1:"*) :;;
      *) PATH=$1:$PATH ;;
    esac
}
# add to front of path
prepend_manpath()
{
  if ! [ -d "$1" ]; then return; fi

  case ":$MANPATH:" in
      *":$1:"*) :;;
      *) MANPATH=$1:$MANPATH ;;
    esac
}

