tap "aws/tap"
tap "denji/nginx"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "wtfutil/wtfutil"
brew "cask"
brew "coreutils"
brew "docker"
brew "readline"
brew "sqlite"
brew "xz"
brew "python"
brew "docker-compose"
brew "fd"
brew "findutils"
brew "fortune"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "mas"
brew "moreutils"
brew "neovim"
brew "node"
brew "openssl"
brew "pinentry-mac"
brew "pyenv"
brew "wget"
brew "zlib"
brew "zsh"
brew "aws/tap/aws-sam-cli"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
cask "alacritty"
cask "atom"
cask "cmake"
cask "docker"
cask "github"
cask "iterm2"
mas "1Password 7", id: 1333542190
mas "iMovie", id: 408981434
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Slack", id: 803453959
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
