tap "aws/tap"
tap "denji/nginx"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/mssql-release"
tap "teamookla/speedtest"
tap "wtfutil/wtfutil"
brew "cmake", link: false
brew "coreutils"
brew "openssl@1.1"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.8"
brew "libffi"
brew "cask"
brew "fd"
brew "findutils"
brew "fortune"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "graphviz"
brew "imagemagick"
brew "ircii"
brew "libyaml"
brew "mas"
brew "mono"
brew "moreutils"
brew "neovim", args: ["HEAD"]
brew "node"
brew "pinentry-mac"
brew "pyenv"
brew "rbenv"
brew "ruby"
brew "subversion"
brew "wget"
brew "zlib"
brew "zsh"
brew "aws/tap/aws-sam-cli"
brew "microsoft/mssql-release/msodbcsql"
brew "microsoft/mssql-release/mssql-tools"
brew "teamookla/speedtest/speedtest"
cask "aerial"
cask "alfred"
cask "cmake"
cask "doteditor"
cask "dotnet-sdk"
cask "doxygen"
cask "font-3270-nerd-font"
cask "font-arimo-nerd-font"
cask "font-aurulentsansmono-nerd-font"
cask "font-bitstreamverasansmono-nerd-font"
cask "font-codenewroman-nerd-font"
cask "font-consolas-for-powerline"
cask "font-cousine-nerd-font"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-droid-sans-mono-for-powerline"
cask "font-droidsansmono-nerd-font"
cask "font-fantasquesansmono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-fira-mono-nerd-font"
cask "font-fontawesome"
cask "font-gohufont-nerd-font"
cask "font-gomono-nerd-font"
cask "font-hack-nerd-font"
cask "font-heavydata-nerd-font"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-inconsolata-g-for-powerline"
cask "font-inconsolata-nerd-font"
cask "font-inconsolatago-nerd-font"
cask "font-inconsolatalgc-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-lekton-nerd-font"
cask "font-menlo-for-powerline"
cask "font-meslo-for-powerline"
cask "font-monofur-for-powerline"
cask "font-monofur-nerd-font"
cask "font-monoid-nerd-font"
cask "font-mononoki-nerd-font"
cask "font-mplus-nerd-font"
cask "font-noto-nerd-font"
cask "font-powerline-symbols"
cask "font-profont-nerd-font"
cask "font-proggycleantt-nerd-font"
cask "font-roboto-mono-for-powerline"
cask "font-robotomono-nerd-font"
cask "font-saucecodepro-nerd-font"
cask "font-source-code-pro-for-powerline"
cask "font-spacemono-nerd-font"
cask "font-tinos-nerd-font"
cask "font-ubuntu-mono-derivative-powerline"
cask "font-ubuntu-nerd-font"
cask "font-ubuntumono-nerd-font"
cask "github"
cask "iglance"
cask "iterm2"
cask "mactex"
cask "powershell"
cask "stay"
cask "textual"
cask "vagrant"
cask "visual-studio-code"
cask "zoomus"
mas "Developer", id: 640199958
mas "Focus Dashcam Organizer", id: 1476008241
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LimeChat", id: 414030210
mas "Magnet", id: 441258766
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Quip", id: 1003160018
mas "Ring", id: 1142753258
mas "Skitch", id: 425955336
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
