tap "aws/tap"
tap "denji/nginx"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/mssql-release"
tap "wtfutil/wtfutil"
brew "awscli"
brew "cask"
brew "coreutils"
brew "cmake"
brew "readline"
brew "sqlite"
brew "svn"
brew "xz"
brew "python"
brew "fd"
brew "findutils"
brew "fortune"
brew "git"
brew "git-lfs"
brew "github/gh/gh"
brew "gnu-sed"
brew "gnupg"
brew "graphviz"
brew "imagemagick"
brew "mas"
brew "mono"
brew "moreutils"
brew "neovim", args:  ['HEAD']
brew "node"
brew "openssl"
brew "pinentry-mac"
brew "pyenv"
brew "rbenv"
brew "wget"
brew "zlib"
brew "zsh"
brew "aws/tap/aws-sam-cli"
brew "microsoft/mssql-release/msodbcsql"
brew "microsoft/mssql-release/mssql-tools"
cask "aerial"
cask "cmake"
cask "doteditor"
cask "dotnet-sdk"
cask "doxygen"
cask "font-codenewroman-nerd-font"
cask "font-consolas-for-powerline"
cask "font-cousine-nerd-font"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-droid-sans-mono-for-powerline"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-fontawesome"
cask "font-go-mono-nerd-font"
cask "font-gohu-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-inconsolata-g-for-powerline"
cask "font-inconsolata-nerd-font"
cask "font-inconsolatago-nerd-font"
cask "font-inconsolatalgc-nerd-font"
cask "font-menlo-for-powerline"
cask "font-meslo-for-powerline"
cask "font-monofur-for-powerline"
cask "font-monofur-nerd-font"
cask "font-monoid-nerd-font"
cask "font-mononoki-nerd-font"
cask "font-mplus-nerd-font"
cask "font-powerline-symbols"
cask "font-profont-nerd-font"
cask "font-proggycleantt-nerd-font"
cask "font-robotomono-nerd-font"
cask "font-share-tech-mono-nerd-font"
cask "font-share-tech-mono-nerd-font-mono"
cask "font-source-code-pro-for-powerline"
cask "font-source-code-pro-nerd-font"
cask "font-space-mono-nerd-font"
cask "font-tinos-nerd-font"
cask "font-ubuntu-mono-derivative-powerline"
cask "font-ubuntu-nerd-font"
cask "font-ubuntu-nerd-font-mono"
cask "font-ubuntumono-nerd-font"
cask "github"
cask "iterm2"
cask "mactex"
cask "vagrant"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Alfred", id: 405843582
mas "Focus Dashcam Organizer", id: 1476008241
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Slack", id: 803453959
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
