[tools]
node = "lts"
python = "latest"
ruby = "latest"
pdm = "latest"
go = "latest"
poetry = "latest"
terraform = "latest"
tree-sitter = "latest"
pre-commit = "latest"
usage = "latest"
terraform-ls = "latest"

[env]
npm_config_update_notifier = "false"
npm_config_progress = "false"
npm_config_update_all = "true"
npm_config_loglevel = "warn"
npm_config_unsafe_perm = "true"
MISE_ENV_FILE = ".env"
