[tools]
node = "lts"
python = "latest"
ruby = "latest"
pdm = "latest"
go = "latest"
terraform = "latest"
tree-sitter = "0.25.10"
pre-commit = "4.3"
usage = "latest"
uv = "latest"
poetry = "latest"
terraform-ls = "latest"

[env]
npm_config_update_notifier = "false"
npm_config_progress = "false"
npm_config_loglevel = "warn"
MISE_ENV_FILE = ".env"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
