[tools]
node = "lts"
python = "3.13"
ruby = "latest"
pdm = "latest"
go = "latest"
terraform = "latest"
tree-sitter = "latest"
pre-commit = "latest"
usage = "latest"
uv = "latest"

[env]
npm_config_update_notifier = "false"
npm_config_progress = "false"
npm_config_loglevel = "warn"
MISE_ENV_FILE = ".env"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
